### ISSUE TITLE
ConsoleSpaming

### ISSUE THREAD

**Issue by Axolotl25** [cyne79/AdvancedLobby#4]
[17:41:09 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredClasses()" because the return value of "de.cyne.advancedlobby.misc.ReflectionHelper.getNMSClass(String)" is null
[17:41:09 WARN]:        at advancedlobby-1.2.jar//de.cyne.advancedlobby.titleapi.TitleAPI.sendTabTitle(TitleAPI.java:64)
[17:41:09 WARN]:        at advancedlobby-1.2.jar//de.cyne.advancedlobby.listener.PlayerJoinListener.lambda$onPlayerJoin$0(PlayerJoinListener.java:91)
[17:41:09 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
[17:41:09 WARN]:        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[17:41:09 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1567)
[17:41:09 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:490)
[17:41:09 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1483)
[17:41:09 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1282)
[17:41:09 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319)
[17:41:09 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ixn075** [comment]
bump

**Comment by ixn075** [comment]
For me it's the same error. I'm on 1.19
